// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProjectForms.Data;

#nullable disable

namespace MiniProjectForms.API.Migrations
{
    [DbContext(typeof(MiniProjectFormsContext))]
    partial class MiniProjectFormsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniProjectForms.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            DeviceId = "OPPO A74",
                            DueDate = new DateTime(2023, 7, 28, 21, 34, 55, 672, DateTimeKind.Local).AddTicks(3406),
                            IsCompleted = false,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            DeviceId = "OPPO A74",
                            DueDate = new DateTime(2023, 7, 28, 21, 34, 55, 672, DateTimeKind.Local).AddTicks(3610),
                            IsCompleted = true,
                            Title = "Task 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
