// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniProjectForms.Data.Migrations
{
    [DbContext(typeof(MiniProjectFormsContext))]
    [Migration("20230716081004_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("MiniProjectForms.Models.TaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            DueDate = new DateTime(2023, 7, 16, 10, 10, 3, 985, DateTimeKind.Local).AddTicks(5912),
                            IsCompleted = false,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            DueDate = new DateTime(2023, 7, 16, 10, 10, 3, 985, DateTimeKind.Local).AddTicks(5947),
                            IsCompleted = true,
                            Title = "Task 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
